// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CMD.proto
// Protobuf Java Version: 4.27.2

package message;

public final class CMD {
  private CMD() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      CMD.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MSG}
   */
  public enum MSG
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <pre>
     * 玩家登录请求
     * </pre>
     *
     * <code>LOGIN_REQ = 1000;</code>
     */
    LOGIN_REQ(1000),
    /**
     * <pre>
     * 玩家登录返回
     * </pre>
     *
     * <code>LOGIN_RESP = 1001;</code>
     */
    LOGIN_RESP(1001),
    /**
     * <pre>
     * 玩家数据同步
     * </pre>
     *
     * <code>PLAYER_DATA_RESP = 2000;</code>
     */
    PLAYER_DATA_RESP(2000),
    /**
     * <pre>
     * 玩家领土同步
     * </pre>
     *
     * <code>PLAYER_TERRITORY_RESP = 2001;</code>
     */
    PLAYER_TERRITORY_RESP(2001),
    /**
     * <pre>
     * 玩家建筑同步
     * </pre>
     *
     * <code>PLAYER_BUILDINGS_RESP = 2051;</code>
     */
    PLAYER_BUILDINGS_RESP(2051),
    /**
     * <pre>
     * 玩家建造建筑
     * </pre>
     *
     * <code>PLAYER_BUILDING_CONSTRUCT_REQ = 2053;</code>
     */
    PLAYER_BUILDING_CONSTRUCT_REQ(2053),
    /**
     * <pre>
     * 建筑升级
     * </pre>
     *
     * <code>PLAYER_BUILDING_LEVEL_UP_REQ = 2054;</code>
     */
    PLAYER_BUILDING_LEVEL_UP_REQ(2054),
    /**
     * <pre>
     * 玩家建筑更新
     * </pre>
     *
     * <code>PLAYER_BUILDING_CONSTRUCT_UPDATE_REQ = 2055;</code>
     */
    PLAYER_BUILDING_CONSTRUCT_UPDATE_REQ(2055),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        MSG.class.getName());
    }
    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <pre>
     * 玩家登录请求
     * </pre>
     *
     * <code>LOGIN_REQ = 1000;</code>
     */
    public static final int LOGIN_REQ_VALUE = 1000;
    /**
     * <pre>
     * 玩家登录返回
     * </pre>
     *
     * <code>LOGIN_RESP = 1001;</code>
     */
    public static final int LOGIN_RESP_VALUE = 1001;
    /**
     * <pre>
     * 玩家数据同步
     * </pre>
     *
     * <code>PLAYER_DATA_RESP = 2000;</code>
     */
    public static final int PLAYER_DATA_RESP_VALUE = 2000;
    /**
     * <pre>
     * 玩家领土同步
     * </pre>
     *
     * <code>PLAYER_TERRITORY_RESP = 2001;</code>
     */
    public static final int PLAYER_TERRITORY_RESP_VALUE = 2001;
    /**
     * <pre>
     * 玩家建筑同步
     * </pre>
     *
     * <code>PLAYER_BUILDINGS_RESP = 2051;</code>
     */
    public static final int PLAYER_BUILDINGS_RESP_VALUE = 2051;
    /**
     * <pre>
     * 玩家建造建筑
     * </pre>
     *
     * <code>PLAYER_BUILDING_CONSTRUCT_REQ = 2053;</code>
     */
    public static final int PLAYER_BUILDING_CONSTRUCT_REQ_VALUE = 2053;
    /**
     * <pre>
     * 建筑升级
     * </pre>
     *
     * <code>PLAYER_BUILDING_LEVEL_UP_REQ = 2054;</code>
     */
    public static final int PLAYER_BUILDING_LEVEL_UP_REQ_VALUE = 2054;
    /**
     * <pre>
     * 玩家建筑更新
     * </pre>
     *
     * <code>PLAYER_BUILDING_CONSTRUCT_UPDATE_REQ = 2055;</code>
     */
    public static final int PLAYER_BUILDING_CONSTRUCT_UPDATE_REQ_VALUE = 2055;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MSG valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MSG forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1000: return LOGIN_REQ;
        case 1001: return LOGIN_RESP;
        case 2000: return PLAYER_DATA_RESP;
        case 2001: return PLAYER_TERRITORY_RESP;
        case 2051: return PLAYER_BUILDINGS_RESP;
        case 2053: return PLAYER_BUILDING_CONSTRUCT_REQ;
        case 2054: return PLAYER_BUILDING_LEVEL_UP_REQ;
        case 2055: return PLAYER_BUILDING_CONSTRUCT_UPDATE_REQ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSG>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MSG> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSG>() {
            public MSG findValueByNumber(int number) {
              return MSG.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.CMD.getDescriptor().getEnumTypes().get(0);
    }

    private static final MSG[] VALUES = values();

    public static MSG valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MSG(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MSG)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCMD.proto*\361\001\n\003MSG\022\010\n\004NONE\020\000\022\016\n\tLOGIN_R" +
      "EQ\020\350\007\022\017\n\nLOGIN_RESP\020\351\007\022\025\n\020PLAYER_DATA_RE" +
      "SP\020\320\017\022\032\n\025PLAYER_TERRITORY_RESP\020\321\017\022\032\n\025PLA" +
      "YER_BUILDINGS_RESP\020\203\020\022\"\n\035PLAYER_BUILDING" +
      "_CONSTRUCT_REQ\020\205\020\022!\n\034PLAYER_BUILDING_LEV" +
      "EL_UP_REQ\020\206\020\022)\n$PLAYER_BUILDING_CONSTRUC" +
      "T_UPDATE_REQ\020\207\020B\t\n\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
